---
- hosts: all
  strategy: free
  gather_facts: true
  #become: true
  tasks:
    - name: Generate preupgrade analysis report
      block:
        - name: Run RIPU preupg
          import_role:
            name: upgrade
            tasks_from: "try.yml"
