---
- hosts: all
  strategy: free
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python2
  tasks:
    - name: Initialize lock and logging
      import_role:
        name: logging
        tasks_from: job_start.yml
      vars:
        job_name: 'RIPU in-place OS upgrade'

    - name: Perform OS upgrade
      block:
        - name: Leapp upgrade
          import_role:
            name: upgrade
            tasks_from: "upgrade.yml"

      always:
        - name: Clean up
          import_role:
            name: logging
            tasks_from: clean_up.yml

